import Provider from "@/components/Provider";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["devanagari"],
});

export const metadata = {
  title: "Travel advisor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places&key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_KEY}`}
          async></script>
      </head>
      <body className={`${poppins.className} bg-gray-100`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
